services:
  - type: web
    name: swara-api
    env: node
    region: singapore # Opsional: Memilih server Singapura agar koneksi ke Indonesia lebih cepat
    rootDir: .
    buildCommand: npm install && npx prisma generate --schema=apps/api/prisma/schema.prisma && npm run build --workspace=apps/api
    startCommand: npm run start:prod --workspace=apps/api
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
